name: github pages

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        env:
            MDBOOK_VERSION: 0.5.3
        steps:
            - uses: actions/checkout@v2

            - name: Install mdbook, mdbook-mermaid, mdbook-last-changed preprocessor
              run: |
                  wget -qO- https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-musl.tar.gz | tar -xz
                  wget -qO- https://github.com/badboy/mdbook-mermaid/releases/download/v0.17.1/mdbook-mermaid-v0.17.1-x86_64-unknown-linux-musl.tar.gz | tar -xz
                  wget -qO- https://github.com/badboy/mdbook-last-changed/releases/download/v0.4.0/mdbook-last-changed-v0.4.0-x86_64-unknown-linux-musl.tar.gz | tar -xz
                  echo "$PWD" >> $GITHUB_PATH

            - name: Install mdbook-gitinfo preprocessor
              run: cargo install mdbook-gitinfo --locked

            - name: Setup mdBook
              uses: peaceiris/actions-mdbook@v2
              with:
                  fetch-depth: 0
                  mdbook-version: "latest"

            - run: mdbook build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  github_token: ${{ secrets.GH_TOKEN_WORKFLOW }}
                  publish_dir: ./book
